### ISSUE TITLE
Duplicated definition of scripts in the layout file

### ISSUE THREAD

**Issue by olivierobert** [malparty/keywords#30]
![image](https://user-images.githubusercontent.com/696529/117755469-76789180-b246-11eb-928c-c620ff117e78.png)

It appears than JS scripts are added twice:

- First in the `head` tag.
- Second at the end of the body `tag` with `defer`.

What are the reasons for this? Would you see an opportunity for an improvement in the way the third party dependency are added to the page to improve performance?

**Comment by malparty** [comment]
Regarding libraries `./lib/*` (JQuery/Bootstrap), these are not build from Webpack, they are static libs managed aside.
So after a double check, I confirm that they are not imported twice: JS files have different content than CSS files.

Regarding `./dist/site/*` libs, there is 2x distinct file: 1 for CSS and the other one for JS. 
CSS is bundled into a JS bunble by the style-loader.

=> I can improve the webpack config so that it would build a CSS file instead of a JS bundle loading css, but IMO this would not have a big change.

> Note that after doing some tests, I decided to separate styles from scripts as loading the style together with all scripts was creating a bad user experience. So now styles are loaded much faster. 


To improve the third party dependencies, I would bring back the libraries into Webpack import (and remove static tags) and work on the webpack configuration so that it can split the output as needed. By doing so, I can also:

- Reduce the size of the final packages (using specific imports from bootstrap SASS & JS and building only the needed components)

- Manage third-parties updates with dependencies control (and get warnings if some dependencies are deprecated)


Let me know if you have any question/request for this issue. I'll keep the issue open meanwhile.

**Comment by olivierobert** [comment]
Actually, I was confused as these are not identical in the sense that it's CSS and then JS 🤕  

> Reduce the size of the final packages (using specific imports from bootstrap SASS & JS and building only the needed components)

Definitely 👍 

> Manage third-parties updates with dependencies control (and get warnings if some dependencies are deprecated)

Github does a good job at that. [Dependabot](https://github.com/dependabot) creates PRs automatically when security audits are enable at the repository level.

In terms of other major improvement, I recommend to concatenate third-party dependencies into a single file for caching purpose (only the app code would change in mots cases). Webpack has this built-in with https://webpack.js.org/plugins/split-chunks-plugin/. 

A common pattern is to have a `vendor.js` file generated. So instead of importing each dependency, only one file would be needed:

```
<script src="~/lib/vendor.js" defer></script>
@await RenderSectionAsync("Scripts", required: false)
<script src="~/dist/site.js" defer></script>
```

That would greatly simplify the maintenance of the layout file. 

Even though HTTP/2 (and HTTP/3) does help in parallelizing script requests, having split chunks is still a good practice.

**Comment by malparty** [comment]
Libs merged into a vendor bundle from official npm packages! ;-)

**Comment by malparty** [comment]
**Update:** After implementing `SplitChunksPLugin`, I realized my libs were imported twice (once in site.js, second in vendor.js). 

Using SplitChunks solved this AND bring the final page loading to 11 files (same) but only 472kb! 😃
